name: Test
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    services:
      - mysql:8.0.27
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.21.3"

      - name: Run user API test
        run: |
          go test -v user_test.go